/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.93.0
  Forc version: 0.62.0
  Fuel-Core version: 0.31.0
*/

import type {
  BytesLike,
  Contract,
  DecodedValue,
  FunctionFragment,
  Interface,
  InvokeFunction,
} from 'fuels';

import type { Enum } from "./common";

export enum AccessErrorInput { NotOwner = 'NotOwner' };
export enum AccessErrorOutput { NotOwner = 'NotOwner' };
export type IdentityInput = Enum<{ Address: AddressInput, ContractId: ContractIdInput }>;
export type IdentityOutput = Enum<{ Address: AddressOutput, ContractId: ContractIdOutput }>;
export enum InitializationErrorInput { CannotReinitialized = 'CannotReinitialized' };
export enum InitializationErrorOutput { CannotReinitialized = 'CannotReinitialized' };
export type StateInput = Enum<{ Uninitialized: [], Initialized: IdentityInput, Revoked: [] }>;
export type StateOutput = Enum<{ Uninitialized: [], Initialized: IdentityOutput, Revoked: [] }>;

export type AddressInput = { bits: string };
export type AddressOutput = AddressInput;
export type ContractIdInput = { bits: string };
export type ContractIdOutput = ContractIdInput;
export type DeregisterEventInput = { contract_id: ContractIdInput };
export type DeregisterEventOutput = { contract_id: ContractIdOutput };
export type OwnershipSetInput = { new_owner: IdentityInput };
export type OwnershipSetOutput = { new_owner: IdentityOutput };
export type RegisterContractEventInput = { contract_id: ContractIdInput, owner: IdentityInput };
export type RegisterContractEventOutput = { contract_id: ContractIdOutput, owner: IdentityOutput };

export interface PropsRegistryContractAbiInterface extends Interface {
  functions: {
    owner: FunctionFragment;
    constructor: FunctionFragment;
    deregister: FunctionFragment;
    register: FunctionFragment;
  };
}

export class PropsRegistryContractAbi extends Contract {
  interface: PropsRegistryContractAbiInterface;
  functions: {
    owner: InvokeFunction<[], StateOutput>;
    constructor: InvokeFunction<[owner: IdentityInput], void>;
    deregister: InvokeFunction<[contractId: ContractIdInput], void>;
    register: InvokeFunction<[contractId: ContractIdInput, owner: IdentityInput], void>;
  };
}
