[project]
authors = ["Props Labs LLC <hello@props.app>"]
entry = "interface.sw"
license = "Apache-2.0"
name = "libraries"

[dependencies]
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.5.1" }